<?php
require_once '../translate/translate.php'; // файл с переводами

$lang = $_POST['lang'];

$_SESSION['lang'] = $lang;

abstract class User {

    protected $_users = [[
    ]];

    protected $translate;

    // конструктор

    function __construct($users, $translate) {

        $this->_users = $users;

        $this->translate = $translate;
    }

    // в качестве аргументов передаю язык из сесси и роль чтобы показать нужную фразу
    public  function sayHello($lang, $role) {

        return $this->translate[$lang]['default'] . " <strong>{$this->_users['role']}\n</strong>" ."{$this->_users['name']} {$this->_users['surname']}\n" . "{$this->translate[$lang][$role]}\n";
    }

}
/**
 * Admin
 */
class Admin extends User {
    public function sayHello($lang, $role)
    {
        return parent::sayHello($lang, $role); // TODO: Change the autogenerated stub
    }
}

/**
 * MANAGER
 */
class Manager extends User{
    public function sayHello($lang, $role)
    {
        return parent::sayHello($lang, $role); // TODO: Change the autogenerated stub
    }
}

/**
 *  Client
 */
class Client extends User{
    public function sayHello($lang, $role)
    {
        return parent::sayHello($lang, $role); // TODO: Change the autogenerated stub
    }
}
